// <auto-generated />
using System;
using HammerSimAPI.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HammerSimAPI.Migrations
{
    [DbContext(typeof(HammerContext))]
    [Migration("20240814170407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HammerSimAPI.Models.Data.RangedWeaponResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShootingResultsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShotsFired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShootingResultsId");

                    b.HasIndex("WeaponId");

                    b.ToTable("RangedWeaponResult");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Data.ShootingResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShootingResults");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.MeleeWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("MeleeWeapon");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.RangedWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfWeapons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShootingResultsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeaponSkill")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShootingResultsId");

                    b.HasIndex("UnitId");

                    b.ToTable("RangedWeapon");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvulnerableSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leasership")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Movement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectiveControl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Save")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubFaction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toughness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitKeywords")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.Wargear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Wargear");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Data.RangedWeaponResult", b =>
                {
                    b.HasOne("HammerSimAPI.Models.Data.ShootingResults", null)
                        .WithMany("IndividualWeaponResults")
                        .HasForeignKey("ShootingResultsId");

                    b.HasOne("HammerSimAPI.Models.Units.RangedWeapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.MeleeWeapon", b =>
                {
                    b.HasOne("HammerSimAPI.Models.Units.Unit", null)
                        .WithMany("MeleeWeapons")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.RangedWeapon", b =>
                {
                    b.HasOne("HammerSimAPI.Models.Data.ShootingResults", null)
                        .WithMany("OutOfRangeWeapons")
                        .HasForeignKey("ShootingResultsId");

                    b.HasOne("HammerSimAPI.Models.Units.Unit", null)
                        .WithMany("RangedWeapons")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.Wargear", b =>
                {
                    b.HasOne("HammerSimAPI.Models.Units.Unit", null)
                        .WithMany("Wargear")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Data.ShootingResults", b =>
                {
                    b.Navigation("IndividualWeaponResults");

                    b.Navigation("OutOfRangeWeapons");
                });

            modelBuilder.Entity("HammerSimAPI.Models.Units.Unit", b =>
                {
                    b.Navigation("MeleeWeapons");

                    b.Navigation("RangedWeapons");

                    b.Navigation("Wargear");
                });
#pragma warning restore 612, 618
        }
    }
}
