<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\HammerSimAPI\HammerSimAPI.csproj" />
    <ProjectReference Include="..\HammerSim.Client\HammerSim.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.2" />
    <PackageReference Include="MudBlazor" Version="7.15.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="2.1.0" />
  </ItemGroup>

</Project>
